<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="br.com.cepa.web.Html" %>
<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><%= Html.escape(request.getAttribute("pageTitle")) %></title><meta name="description" content="CEPA: curadoria de vinhos para escolher com confiança."><link rel="stylesheet" href="<%= request.getContextPath() %>/assets/styles.css"></head>
<body>
<div class="announcement">Projeto acadêmico CEPA · Vinheria Agnello · Fase 2</div>
<header class="site-header"><div class="header-inner"><a class="brand" href="<%= request.getContextPath() %>/inicio" aria-label="CEPA, ir para o início"><span class="brand-mark">◖</span><span>CEPA</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav">Menu <span>☰</span></button><nav id="main-nav" class="main-nav" aria-label="Navegação principal"><a class="<%= "inicio".equals(request.getAttribute("active")) ? "active" : "" %>" href="<%= request.getContextPath() %>/inicio">Início</a><a class="<%= "catalogo".equals(request.getAttribute("active")) ? "active" : "" %>" href="<%= request.getContextPath() %>/catalogo">Catálogo</a><a class="<%= "quiz".equals(request.getAttribute("active")) ? "active" : "" %>" href="<%= request.getContextPath() %>/quiz">Quiz de Paladar</a><a class="<%= "adega".equals(request.getAttribute("active")) ? "active" : "" %>" href="<%= request.getContextPath() %>/adega">Minha Adega</a><a class="<%= "painel".equals(request.getAttribute("active")) ? "active" : "" %>" href="<%= request.getContextPath() %>/painel">Painel da Vinheria</a></nav><a class="cart-link" href="<%= request.getContextPath() %>/carrinho" aria-label="Carrinho com <%= request.getAttribute("cartCount") %> itens">♧ <span><%= request.getAttribute("cartCount") %></span></a></div></header>
<% if (request.getAttribute("notice") != null) { %><div class="notice" role="status"><%= Html.escape(request.getAttribute("notice")) %></div><% } %>
<main id="conteudo"><jsp:include page="${contentPage}" /></main>
<footer class="site-footer"><div class="container footer-grid"><div><div class="footer-brand">◖ CEPA</div><p>O vinho certo, para você, na condição certa, até você.</p><small>Protótipo acadêmico · Sem vendas ou pagamentos reais.</small></div><div><strong>Explore</strong><a href="<%= request.getContextPath() %>/catalogo">Catálogo</a><a href="<%= request.getContextPath() %>/quiz">Quiz de paladar</a></div><div><strong>Vinheria</strong><a href="<%= request.getContextPath() %>/painel">Painel do lojista</a><small>Dados: <%= Html.escape(request.getAttribute("mode")) %></small></div></div></footer>
<script src="<%= request.getContextPath() %>/assets/app.js" defer></script></body></html>
